/**
 * src/config/sources.ts
 * EuroPulse Central Feed Source Registry.
 *
 * All verified news RSS/Atom, job API, and link-out sources for European
 * business and careers intelligence live here.
 *
 * Rules:
 * - Headline, publisher name, date, short excerpt (<= 200 chars), and prominent link to original.
 * - Never store full text; never republish images unless feed provides licensed URL.
 * - API keys must ONLY be read from GitHub Actions secrets.
 * - Missing secrets cause the source to be skipped with a clear log; build never fails.
 */

export type SourceType = 'news' | 'jobs' | 'official';
export type FeedType = 'rss' | 'atom' | 'json-api' | 'ats-api' | 'link-out';

export interface FeedSource {
  id: string;
  name: string;
  type: SourceType;
  country: string; // ISO2, country slug, or "EU"
  language: string; // ISO 639-1 ('en', 'de', 'fr', 'it', 'es', 'sv', 'nl', etc.)
  feedType: FeedType;
  url: string;
  requiredSecret?: string;
  refreshIntervalMins: number;
  enabled: boolean;
  attribution: string;
  termsNote: string;
}

export const feedSources: FeedSource[] = [
  // ==========================================
  // PAN-EUROPEAN & EU AFFAIRS (News & Official)
  // ==========================================
  {
    id: 'euronews-business',
    name: 'Euronews Business',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.euronews.com/rss?format=mrss&level=theme&name=business',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Euronews. Content licensed via public MRSS feed. Direct links to euronews.com.',
    termsNote: 'Public RSS feed. Limited to title, date, excerpt and direct link back to publisher.',
  },
  {
    id: 'euronews-europe',
    name: 'Euronews Europe',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.euronews.com/rss?format=mrss&level=theme&name=news',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Euronews. Content licensed via public MRSS feed.',
    termsNote: 'Public RSS feed with original article permalinks.',
  },
  {
    id: 'euractiv',
    name: 'Euractiv',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.euractiv.com/feed/',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Euractiv EU Policy News. Excerpts and headlines only.',
    termsNote: 'Public RSS feed for EU policy and industrial affairs.',
  },
  {
    id: 'politico-eu',
    name: 'Politico Europe',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.politico.eu/feed/',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Politico Europe. Excerpt and headline with canonical link.',
    termsNote: 'Public RSS feed syndication terms respected.',
  },
  {
    id: 'euobserver',
    name: 'EUobserver',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://euobserver.com/rss',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'EUobserver Independent European News.',
    termsNote: 'Public RSS headlines and short descriptions only.',
  },
  {
    id: 'ec-press-corner',
    name: 'European Commission Press Corner',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://ec.europa.eu/commission/presscorner/api/rss?language=en',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'European Union / European Commission Press Corner (Re-use permitted under CC BY 4.0 / Commission Decision 2011/833/EU).',
    termsNote: 'Official EU Open Data and public announcements feed.',
  },
  {
    id: 'eurostat-news',
    name: 'Eurostat News Releases',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://ec.europa.eu/eurostat/api/rss/news',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Eurostat, Statistical Office of the European Union.',
    termsNote: 'Official EU statistical public release feed.',
  },
  {
    id: 'ecb-press',
    name: 'European Central Bank',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.ecb.europa.eu/rss/press.html',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'European Central Bank (ECB) Press Releases.',
    termsNote: 'Official central banking policy releases.',
  },
  {
    id: 'eurofound-news',
    name: 'Eurofound News',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.eurofound.europa.eu/en/rss/news',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'Eurofound (European Foundation for the Improvement of Living and Working Conditions).',
    termsNote: 'Official EU agency feed on working conditions and industrial relations.',
  },
  {
    id: 'eea-press',
    name: 'European Environment Agency',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.eea.europa.eu/en/newsroom/news/RSS',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'European Environment Agency (EEA).',
    termsNote: 'Official EU agency newsroom RSS.',
  },
  {
    id: 'eu-osha-news',
    name: 'EU-OSHA News',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://osha.europa.eu/en/rss-feeds/news.xml',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'EU-OSHA (European Agency for Safety and Health at Work).',
    termsNote: 'Official EU agency feed on workplace safety and regulations.',
  },
  {
    id: 'cedefop-news',
    name: 'Cedefop News',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.cedefop.europa.eu/en/rss-feed/news',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'Cedefop (European Centre for the Development of Vocational Training).',
    termsNote: 'Official EU agency feed on vocational education and European skills.',
  },
  {
    id: 'oecd-newsroom',
    name: 'OECD Newsroom',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.oecd.org/en/about/newsroom.rss',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'OECD (Organisation for Economic Co-operation and Development).',
    termsNote: 'Public newsroom dispatches on employment and economics.',
  },

  // ==========================================
  // NATIONAL OUTLETS & BROADCASTERS (By Country)
  // ==========================================
  // Germany
  {
    id: 'dw-business',
    name: 'Deutsche Welle Business',
    type: 'news',
    country: 'germany',
    language: 'en',
    feedType: 'rss',
    url: 'https://rss.dw.com/rdf/rss-en-bus',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Deutsche Welle (DW). German public broadcaster international service.',
    termsNote: 'Public RSS feed. Limited to headline, excerpt and link.',
  },
  {
    id: 'dw-europe',
    name: 'Deutsche Welle Europe',
    type: 'news',
    country: 'germany',
    language: 'en',
    feedType: 'rss',
    url: 'https://rss.dw.com/rdf/rss-en-eu',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Deutsche Welle (DW).',
    termsNote: 'Public RSS feed.',
  },
  {
    id: 'tagesschau-wirtschaft',
    name: 'Tagesschau Wirtschaft',
    type: 'news',
    country: 'germany',
    language: 'de',
    feedType: 'rss',
    url: 'https://www.tagesschau.de/wirtschaft/index~rss2.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'ARD Tagesschau. German public service broadcasting network.',
    termsNote: 'Public RSS feed for headlines and short excerpts.',
  },
  {
    id: 'handelsblatt',
    name: 'Handelsblatt',
    type: 'news',
    country: 'germany',
    language: 'de',
    feedType: 'rss',
    url: 'https://www.handelsblatt.com/contentexport/feed/top-themen',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Handelsblatt Media Group. Public headlines only.',
    termsNote: 'Public headlines feed; links directly to paywall/article on handelsblatt.com.',
  },

  // France
  {
    id: 'france24-en',
    name: 'France 24',
    type: 'news',
    country: 'france',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.france24.com/en/rss',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'France 24. French public international broadcaster.',
    termsNote: 'Public RSS feed with direct permalinks.',
  },
  {
    id: 'rfi-en',
    name: 'RFI (Radio France Internationale)',
    type: 'news',
    country: 'france',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.rfi.fr/en/rss',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Radio France Internationale.',
    termsNote: 'Public RSS headlines and brief excerpts.',
  },
  {
    id: 'les-echos-eco',
    name: 'Les Echos',
    type: 'news',
    country: 'france',
    language: 'fr',
    feedType: 'rss',
    url: 'https://services.lesechos.fr/rss/les-echos-economie.xml',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Les Echos. French business daily.',
    termsNote: 'Public RSS headlines and short summaries only.',
  },
  {
    id: 'le-monde-eco',
    name: 'Le Monde Économie',
    type: 'news',
    country: 'france',
    language: 'fr',
    feedType: 'rss',
    url: 'https://www.lemonde.fr/economie/rss_full.xml',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Le Monde. Economic news desk.',
    termsNote: 'Public RSS feed; directs visitors to lemonde.fr.',
  },
  {
    id: 'maddyness',
    name: 'Maddyness',
    type: 'news',
    country: 'france',
    language: 'fr',
    feedType: 'rss',
    url: 'https://www.maddyness.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Maddyness. French startup and innovation media.',
    termsNote: 'Public RSS feed for French startup and venture news.',
  },

  // Netherlands
  {
    id: 'nos-nieuws',
    name: 'NOS Nieuws',
    type: 'news',
    country: 'netherlands',
    language: 'nl',
    feedType: 'rss',
    url: 'https://feeds.nos.nl/nosnieuwsalgemeen',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Nederlandse Omroep Stichting (NOS). Dutch public broadcaster.',
    termsNote: 'Public RSS feed for news headlines and brief summaries.',
  },
  {
    id: 'nl-times',
    name: 'NL Times',
    type: 'news',
    country: 'netherlands',
    language: 'en',
    feedType: 'rss',
    url: 'https://nltimes.nl/rss.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'NL Times. English-language Dutch news publication.',
    termsNote: 'Public RSS feed with direct article links.',
  },
  {
    id: 'fd-nl',
    name: 'Het Financieele Dagblad',
    type: 'news',
    country: 'netherlands',
    language: 'nl',
    feedType: 'rss',
    url: 'https://fd.nl/?rss',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Het Financieele Dagblad (FD). Public headlines only.',
    termsNote: 'Public headlines feed only. Never republishes article body.',
  },

  // Italy
  {
    id: 'ansa-en',
    name: 'ANSA English',
    type: 'news',
    country: 'italy',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Agenzia Nazionale Stampa Associata (ANSA). Italian leading news agency.',
    termsNote: 'Public RSS wire feed with links to ansa.it.',
  },
  {
    id: 'il-sole-24-ore',
    name: 'Il Sole 24 Ore',
    type: 'news',
    country: 'italy',
    language: 'it',
    feedType: 'rss',
    url: 'https://www.ilsole24ore.com/rss/economia.xml',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Il Sole 24 Ore. Italian financial daily. Public headlines only.',
    termsNote: 'Public headlines feed for Italian economics and industry.',
  },
  {
    id: 'rai-news',
    name: 'RAI News Economia',
    type: 'news',
    country: 'italy',
    language: 'it',
    feedType: 'rss',
    url: 'https://www.rainews.it/rss/economia',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'RAI - Radiotelevisione Italiana. Italian public broadcaster.',
    termsNote: 'Public RSS headlines from national broadcaster.',
  },

  // Spain
  {
    id: 'rtve-noticias',
    name: 'RTVE Noticias',
    type: 'news',
    country: 'spain',
    language: 'es',
    feedType: 'rss',
    url: 'https://api.rtve.es/api/noticias/rss',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Corporación de Radio y Televisión Española (RTVE).',
    termsNote: 'Public RSS feed from Spanish state broadcaster.',
  },
  {
    id: 'el-pais-en',
    name: 'El País English',
    type: 'news',
    country: 'spain',
    language: 'en',
    feedType: 'rss',
    url: 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/inenglish/portada',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'El País English Edition. PRISA Media.',
    termsNote: 'Public RSS feed; directs reader to original articles.',
  },
  {
    id: 'cinco-dias',
    name: 'Cinco Días',
    type: 'news',
    country: 'spain',
    language: 'es',
    feedType: 'rss',
    url: 'https://feeds.elpais.com/mrss-s/pages/ep/site/cincodias.com/portada',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Cinco Días (El País Economía).',
    termsNote: 'Spanish business and market daily RSS.',
  },
  {
    id: 'expansion',
    name: 'Expansión',
    type: 'news',
    country: 'spain',
    language: 'es',
    feedType: 'rss',
    url: 'https://e00-expansion.uecdn.es/rss/portada.xml',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Expansión. Unidad Editorial.',
    termsNote: 'Spanish financial publication RSS feed.',
  },

  // Sweden & Nordics
  {
    id: 'svt-nyheter',
    name: 'SVT Nyheter',
    type: 'news',
    country: 'sweden',
    language: 'sv',
    feedType: 'rss',
    url: 'https://www.svt.se/nyheter/rss.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Sveriges Television (SVT). Swedish national public broadcaster.',
    termsNote: 'Public RSS feed with article permalinks.',
  },
  {
    id: 'sr-english',
    name: 'Sveriges Radio English',
    type: 'news',
    country: 'sweden',
    language: 'en',
    feedType: 'rss',
    url: 'https://api.sr.se/api/rss/program/2054',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Sveriges Radio. Swedish public radio English service.',
    termsNote: 'Public RSS broadcast headlines and audio links.',
  },
  {
    id: 'the-local-se',
    name: 'The Local Sweden',
    type: 'news',
    country: 'sweden',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.thelocal.se/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'The Local Sweden. European news in English.',
    termsNote: 'Public RSS feed for international professionals in Sweden.',
  },
  {
    id: 'dr-nyheder',
    name: 'DR Nyheder',
    type: 'news',
    country: 'denmark',
    language: 'da',
    feedType: 'rss',
    url: 'https://www.dr.dk/nyheder/service/feeds/allseneste',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Danmarks Radio (DR). Danish public broadcaster.',
    termsNote: 'Public RSS news feed.',
  },
  {
    id: 'the-local-dk',
    name: 'The Local Denmark',
    type: 'news',
    country: 'denmark',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.thelocal.dk/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'The Local Denmark.',
    termsNote: 'Public RSS feed.',
  },
  {
    id: 'nrk-nyheter',
    name: 'NRK Nyheter',
    type: 'news',
    country: 'norway',
    language: 'no',
    feedType: 'rss',
    url: 'https://www.nrk.no/nyheter/siste.rss',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Norsk rikskringkasting (NRK). Norwegian government-owned radio and TV.',
    termsNote: 'Public RSS feed from Norwegian public broadcaster.',
  },
  {
    id: 'the-local-no',
    name: 'The Local Norway',
    type: 'news',
    country: 'norway',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.thelocal.no/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'The Local Norway.',
    termsNote: 'Public RSS feed.',
  },
  {
    id: 'yle-news',
    name: 'YLE News (English)',
    type: 'news',
    country: 'finland',
    language: 'en',
    feedType: 'rss',
    url: 'https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Yleisradio (YLE). Finnish national public broadcasting company.',
    termsNote: 'Public RSS feed from Finnish public broadcaster.',
  },

  // Ireland & UK
  {
    id: 'rte-business',
    name: 'RTÉ Business',
    type: 'news',
    country: 'ireland',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.rte.ie/feeds/rss/?index=/news/business/',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Raidió Teilifís Éireann (RTÉ). Irish public service broadcaster.',
    termsNote: 'Public RSS business feed.',
  },
  {
    id: 'irish-times-biz',
    name: 'The Irish Times Business',
    type: 'news',
    country: 'ireland',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.irishtimes.com/arc/outboundfeeds/rss/category/business/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'The Irish Times. Irish business news and analysis.',
    termsNote: 'Public RSS feed for business headlines.',
  },
  {
    id: 'bbc-business',
    name: 'BBC News Business',
    type: 'news',
    country: 'gb',
    language: 'en',
    feedType: 'rss',
    url: 'https://feeds.bbci.co.uk/news/business/rss.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'BBC News. British Broadcasting Corporation.',
    termsNote: 'Public BBC RSS feed. Displayed with headline and link.',
  },
  {
    id: 'bbc-europe',
    name: 'BBC News Europe',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://feeds.bbci.co.uk/news/world/europe/rss.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'BBC News Europe.',
    termsNote: 'Public BBC RSS feed.',
  },
  {
    id: 'guardian-business',
    name: 'The Guardian Business',
    type: 'news',
    country: 'gb',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.theguardian.com/business/rss',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'The Guardian. Guardian News & Media Limited.',
    termsNote: 'Public RSS feed for financial and corporate reporting.',
  },
  {
    id: 'city-am',
    name: 'City AM',
    type: 'news',
    country: 'gb',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.cityam.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'City A.M. London business and financial newspaper.',
    termsNote: 'Public RSS feed.',
  },

  // Belgium, Austria, Switzerland, Poland, Portugal
  {
    id: 'vrt-nws',
    name: 'VRT NWS',
    type: 'news',
    country: 'belgium',
    language: 'nl',
    feedType: 'rss',
    url: 'https://www.vrt.be/vrtnws/nl.rss.artikels.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Vlaamse Radio- en Televisieomroeporganisatie (VRT).',
    termsNote: 'Belgian public broadcaster RSS.',
  },
  {
    id: 'brussels-times',
    name: 'The Brussels Times',
    type: 'news',
    country: 'belgium',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.brusselstimes.com/feed',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'The Brussels Times. English-language Belgian daily.',
    termsNote: 'Public RSS feed for Belgian and European affairs.',
  },
  {
    id: 'orf-news',
    name: 'ORF News',
    type: 'news',
    country: 'austria',
    language: 'de',
    feedType: 'rss',
    url: 'https://rss.orf.at/news.xml',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Österreichischer Rundfunk (ORF). Austrian public broadcaster.',
    termsNote: 'Public RSS news feed.',
  },
  {
    id: 'the-local-at',
    name: 'The Local Austria',
    type: 'news',
    country: 'austria',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.thelocal.at/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'The Local Austria.',
    termsNote: 'Public RSS feed.',
  },
  {
    id: 'swissinfo-en',
    name: 'SWI swissinfo.ch',
    type: 'news',
    country: 'switzerland',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.swissinfo.ch/eng/rss',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'SWI swissinfo.ch. Swiss Broadcasting Corporation (SRG SSR).',
    termsNote: 'Public RSS feed for Swiss international news.',
  },
  {
    id: 'nzz-wirtschaft',
    name: 'Neue Zürcher Zeitung',
    type: 'news',
    country: 'switzerland',
    language: 'de',
    feedType: 'rss',
    url: 'https://www.nzz.ch/wirtschaft.rss',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Neue Zürcher Zeitung (NZZ). Public headlines only.',
    termsNote: 'Public headlines feed; links directly to nzz.ch.',
  },
  {
    id: 'tvp-world',
    name: 'TVP World',
    type: 'news',
    country: 'poland',
    language: 'en',
    feedType: 'rss',
    url: 'https://tvpworld.com/rss',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'TVP World. Polish public television English channel.',
    termsNote: 'Public RSS news feed.',
  },
  {
    id: 'notes-from-poland',
    name: 'Notes from Poland',
    type: 'news',
    country: 'poland',
    language: 'en',
    feedType: 'rss',
    url: 'https://notesfrompoland.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Notes from Poland Foundation.',
    termsNote: 'Public RSS feed covering Polish business, politics and society.',
  },
  {
    id: 'portugal-resident',
    name: 'Portugal Resident',
    type: 'news',
    country: 'portugal',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.portugalresident.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Portugal Resident. English news in Portugal.',
    termsNote: 'Public RSS news feed.',
  },
  {
    id: 'rtp-noticias',
    name: 'RTP Notícias',
    type: 'news',
    country: 'portugal',
    language: 'pt',
    feedType: 'rss',
    url: 'https://www.rtp.pt/noticias/rss',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Rádio e Televisão de Portugal (RTP). Portuguese public service broadcaster.',
    termsNote: 'Public RSS feed.',
  },

  // ==========================================
  // STARTUPS, TECH & INNOVATION
  // ==========================================
  {
    id: 'sifted',
    name: 'Sifted',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://sifted.eu/feed/',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Sifted. Backed by the Financial Times. European startup intelligence.',
    termsNote: 'Public RSS feed for European venture capital and tech scaleups.',
  },
  {
    id: 'tech-eu',
    name: 'Tech.eu',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://tech.eu/feed/',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Tech.eu. European technology ecosystem news.',
    termsNote: 'Public RSS feed with permalinks.',
  },
  {
    id: 'eu-startups',
    name: 'EU-Startups',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.eu-startups.com/feed/',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'EU-Startups. Leading online publication about startups in Europe.',
    termsNote: 'Public RSS feed covering funding rounds and startup developments.',
  },
  {
    id: 'silicon-canals',
    name: 'Silicon Canals',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://siliconcanals.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Silicon Canals. Benelux & European technology journalism.',
    termsNote: 'Public RSS feed.',
  },
  {
    id: 'the-next-web',
    name: 'The Next Web',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://thenextweb.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'TNW (The Next Web). Financial Times company.',
    termsNote: 'Public RSS feed for European digital and tech ecosystem.',
  },

  // ==========================================
  // INDUSTRY VERTICALS
  // ==========================================
  // Automotive & Mobility
  {
    id: 'autonews-europe',
    name: 'Automotive News Europe',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://europe.autonews.com/rss/all',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Automotive News Europe. Crain Communications.',
    termsNote: 'Public RSS feed for European automotive industry and EV supply chain.',
  },
  {
    id: 'electrive',
    name: 'electrive.com',
    type: 'news',
    country: 'germany',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.electrive.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'electrive.com. News service for electric mobility in Europe.',
    termsNote: 'Public RSS feed on electromobility and battery manufacturing.',
  },

  // Robotics & Manufacturing
  {
    id: 'robot-report',
    name: 'The Robot Report',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.therobotreport.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'The Robot Report. WTWH Media.',
    termsNote: 'Public RSS feed on industrial automation and robotics engineering.',
  },
  {
    id: 'manufacturing-global',
    name: 'Manufacturing Global',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://manufacturingglobal.com/rss',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Manufacturing Digital / BizClik Media.',
    termsNote: 'Public RSS feed on European industrial manufacturing.',
  },

  // Aerospace & Defence
  {
    id: 'aerospace-global-news',
    name: 'Aerospace Global News',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://aerospaceglobalnews.com/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Aerospace Global News.',
    termsNote: 'Public RSS feed on European commercial aviation and defence.',
  },
  {
    id: 'esa-news',
    name: 'European Space Agency (ESA)',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.esa.int/rssfeed/Our_Activities',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'European Space Agency (ESA). Intergovernmental space organisation.',
    termsNote: 'Official ESA public newsfeed.',
  },

  // Fashion & Textiles
  {
    id: 'fashionunited',
    name: 'FashionUnited Europe',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://fashionunited.com/rss-news',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'FashionUnited. International B2B fashion network.',
    termsNote: 'Public RSS feed for European luxury, retail and circular fashion news.',
  },

  // Technology & Semiconductors
  {
    id: 'ee-times-europe',
    name: 'EE Times Europe',
    type: 'news',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.eetimes.eu/feed/',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'EE Times Europe. AspenCore.',
    termsNote: 'Public RSS feed for microelectronics, chips, and European semiconductor design.',
  },

  // Careers & Higher Education
  {
    id: 'eures-news',
    name: 'EURES News',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://ec.europa.eu/eures/public/rss/news_en.xml',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'EURES (European Job Mobility Portal). European Labour Authority.',
    termsNote: 'Official European Commission / ELA public information feed.',
  },
  {
    id: 'study-in-europe',
    name: 'Study in Europe',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://studyineurope.eu/feed',
    refreshIntervalMins: 240,
    enabled: true,
    attribution: 'Study in Europe. European Commission higher education portal.',
    termsNote: 'Public portal for European academic programmes.',
  },
  {
    id: 'daad-news',
    name: 'DAAD News',
    type: 'official',
    country: 'germany',
    language: 'en',
    feedType: 'rss',
    url: 'https://www.daad.de/en/the-daad/postamble/feed/',
    refreshIntervalMins: 240,
    enabled: true,
    attribution: 'DAAD (German Academic Exchange Service).',
    termsNote: 'Public information feed for German scholarships and international study.',
  },
  {
    id: 'erasmus-plus-news',
    name: 'Erasmus+ News',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://erasmus-plus.ec.europa.eu/rss.xml',
    refreshIntervalMins: 240,
    enabled: true,
    attribution: 'Erasmus+ Programme. European Commission.',
    termsNote: 'Official EU programme for education, training, youth and sport.',
  },

  // ==========================================
  // JOB SOURCES (Automated APIs & Feeds)
  // ==========================================
  {
    id: 'arbeitnow',
    name: 'Arbeitnow Jobs API',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'json-api',
    url: 'https://www.arbeitnow.com/api/job-board-api',
    refreshIntervalMins: 30,
    enabled: true,
    attribution: 'Arbeitnow Job Board API. Free public endpoint for European career openings.',
    termsNote: 'Public API provided for third-party discovery with direct apply link to employer.',
  },
  {
    id: 'adzuna',
    name: 'Adzuna European Jobs API',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'json-api',
    url: 'https://api.adzuna.com/v1/api/jobs',
    requiredSecret: 'ADZUNA_APP_ID',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Adzuna API. European job listings.',
    termsNote: 'Official API requires ADZUNA_APP_ID & ADZUNA_APP_KEY. Free tier capped at 250 calls/day.',
  },
  {
    id: 'bundesagentur-jobsuche',
    name: 'Bundesagentur für Arbeit Jobsuche API',
    type: 'jobs',
    country: 'germany',
    language: 'de',
    feedType: 'json-api',
    url: 'https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v4/app/jobs',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Bundesagentur für Arbeit (BA). Germany Federal Employment Agency.',
    termsNote: 'Official public API for job listings in Germany. Free access for third-party job search.',
  },
  {
    id: 'france-travail',
    name: 'France Travail "Offres d\'emploi" API',
    type: 'jobs',
    country: 'france',
    language: 'fr',
    feedType: 'json-api',
    url: 'https://api.francetravail.io/partenaire/offresdemploi/v2/offres/search',
    requiredSecret: 'FRANCE_TRAVAIL_CLIENT_ID',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'France Travail (Pôle Emploi). French public employment service.',
    termsNote: 'Official API via France Travail Partenaire platform. Requires FRANCE_TRAVAIL_CLIENT_ID & FRANCE_TRAVAIL_CLIENT_SECRET.',
  },
  {
    id: 'reed-uk',
    name: 'Reed.co.uk API',
    type: 'jobs',
    country: 'gb',
    language: 'en',
    feedType: 'json-api',
    url: 'https://www.reed.co.uk/api/1.0/search',
    requiredSecret: 'REED_API_KEY',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Reed Specialist Recruitment Limited.',
    termsNote: 'Official Reed API requires free developer key stored in REED_API_KEY secret.',
  },
  {
    id: 'jooble',
    name: 'Jooble API',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'json-api',
    url: 'https://jooble.org/api/',
    requiredSecret: 'JOOBLE_API_KEY',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Jooble API. International job aggregator.',
    termsNote: 'Requires JOOBLE_API_KEY secret. Links directly to original posting.',
  },
  {
    id: 'remotive',
    name: 'Remotive European Remote Jobs',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'json-api',
    url: 'https://remotive.com/api/remote-jobs',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Remotive API. Curated tech and remote opportunities.',
    termsNote: 'Public API. Filtered for roles open to European candidates.',
  },
  {
    id: 'himalayas',
    name: 'Himalayas Remote Jobs API',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'json-api',
    url: 'https://himalayas.app/jobs/api',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'Himalayas API.',
    termsNote: 'Public API endpoint. Filtered for Europe/EU timezone roles.',
  },
  {
    id: 'weworkremotely',
    name: 'We Work Remotely Tech Feed',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://weworkremotely.com/categories/remote-programming-jobs.rss',
    refreshIntervalMins: 120,
    enabled: true,
    attribution: 'We Work Remotely RSS.',
    termsNote: 'Public RSS feed. Filtered for Europe-accessible roles.',
  },
  {
    id: 'eu-osha-vacancies',
    name: 'EU-OSHA Vacancies RSS',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'rss',
    url: 'https://osha.europa.eu/en/about-eu-osha/careers/vacancies/rss.xml',
    refreshIntervalMins: 180,
    enabled: true,
    attribution: 'EU-OSHA Agency Vacancies.',
    termsNote: 'Official EU institution career RSS feed.',
  },

  // ==========================================
  // ATS DIRECT ENDPOINTS (Greenhouse / Lever / Recruitee)
  // ==========================================
  {
    id: 'ats-greenhouse-aggregate',
    name: 'Public Greenhouse Job Boards',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'ats-api',
    url: 'https://boards-api.greenhouse.io/v1/boards/{token}/jobs',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Greenhouse Public Job Board API (direct employer boards).',
    termsNote: 'Official public endpoints published by employers for career page display.',
  },
  {
    id: 'ats-lever-aggregate',
    name: 'Public Lever Postings',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'ats-api',
    url: 'https://api.lever.co/v0/postings/{token}',
    refreshIntervalMins: 60,
    enabled: true,
    attribution: 'Lever Public Postings API (direct employer boards).',
    termsNote: 'Official public endpoints for employer job postings.',
  },

  // ==========================================
  // LINK-OUT ONLY PORTALS (No automated scraping)
  // ==========================================
  {
    id: 'epso',
    name: 'EPSO (EU Careers)',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'link-out',
    url: 'https://eu-careers.europa.eu/en/job-opportunities/open-vacancies',
    refreshIntervalMins: 0,
    enabled: true,
    attribution: 'European Personnel Selection Office (EPSO).',
    termsNote: 'Link-out only portal. No automated scraping per EuroPulse strict policy.',
  },
  {
    id: 'eures-portal',
    name: 'EURES Job Portal',
    type: 'official',
    country: 'EU',
    language: 'en',
    feedType: 'link-out',
    url: 'https://eures.ec.europa.eu/jobseekers-and-employers/find-job_en',
    refreshIntervalMins: 0,
    enabled: true,
    attribution: 'European Labour Authority (ELA) / EURES.',
    termsNote: 'Link-out only portal. Directed search links provided.',
  },
  {
    id: 'linkedin-jobs',
    name: 'LinkedIn Jobs',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'link-out',
    url: 'https://www.linkedin.com/jobs/search/',
    refreshIntervalMins: 0,
    enabled: true,
    attribution: 'LinkedIn Corporation.',
    termsNote: 'Link-out only. User query deep-linked directly in browser tab.',
  },
  {
    id: 'indeed-eu',
    name: 'Indeed',
    type: 'jobs',
    country: 'EU',
    language: 'en',
    feedType: 'link-out',
    url: 'https://www.indeed.com/',
    refreshIntervalMins: 0,
    enabled: true,
    attribution: 'Indeed, Inc.',
    termsNote: 'Link-out only. No scraping per robots.txt & terms.',
  },
  {
    id: 'stepstone',
    name: 'StepStone',
    type: 'jobs',
    country: 'germany',
    language: 'de',
    feedType: 'link-out',
    url: 'https://www.stepstone.de/',
    refreshIntervalMins: 0,
    enabled: true,
    attribution: 'The StepStone Group.',
    termsNote: 'Link-out search deep links only.',
  },
  {
    id: 'welcome-to-the-jungle',
    name: 'Welcome to the Jungle',
    type: 'jobs',
    country: 'france',
    language: 'en',
    feedType: 'link-out',
    url: 'https://www.welcometothejungle.com/',
    refreshIntervalMins: 0,
    enabled: true,
    attribution: 'Welcome to the Jungle (Coruscant SAS).',
    termsNote: 'Link-out search links.',
  }
];

export function getSourceById(id: string): FeedSource | undefined {
  return feedSources.find(s => s.id === id);
}

export function getActiveNewsSources(): FeedSource[] {
  return feedSources.filter(s => (s.type === 'news' || s.type === 'official') && s.enabled && s.feedType !== 'link-out');
}

export function getActiveJobSources(): FeedSource[] {
  return feedSources.filter(s => s.type === 'jobs' && s.enabled && s.feedType !== 'link-out');
}
